# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmYMY8G_RPWQjAJpZ0FLbGwvaZ6aXKJz
"""

!pip install praw spacy bertopic sentence-transformers umap-learn hdbscan nltk gensim
!python -m spacy download en_core_web_sm

import praw
import pandas as pd

# IMPORTANT: Replace "YOUR_CLIENT_ID" and "YOUR_CLIENT_SECRET" with your actual Reddit API credentials.
# You can obtain these by creating an application on Reddit's developer platform.
# For more information, visit: https://www.reddit.com/prefs/apps
reddit = praw.Reddit(
    client_id="YetFLz20wt1E6AmxeKZp9A",
    client_secret="W89zVKqYqr1LHfFe4pYfR9_zggowHQ",
    user_agent="mental_health_research:v1.0",
    check_for_async=False
)

reddit.read_only = True

subreddits = ["adhd", "adhdwomen", "mentalhealth", "malementalhealth"]

posts = []

for sub in subreddits:
    subreddit = reddit.subreddit(sub)
    for submission in subreddit.top(time_filter="year", limit=1000):
        posts.append({
            "subreddit": sub,
            "text": submission.title + " " + submission.selftext,
        })

df = pd.DataFrame(posts)
df = df[df['text'].notna()]
df = df[df['text'] != ""]
print("Collected:", len(df))

import spacy
nlp = spacy.load("en_core_web_sm")

def process_text(text):
    doc = nlp(text)

    tokens = []
    entities = []

    for token in doc:
        if token.is_alpha and not token.is_stop:
            tokens.append(token.lemma_.lower())

    for ent in doc.ents:
        # Keep only meaningful entity types
        if ent.label_ in ["PERSON", "ORG", "GPE", "PRODUCT", "EVENT"]:
            entities.append(ent.text.lower())

    clean_text = " ".join(tokens)
    entity_text = " ".join(entities)

    return clean_text, entity_text

df[['clean_text', 'entity_text']] = df['text'].apply(
    lambda x: pd.Series(process_text(x))
)

df['enhanced_text'] = df['clean_text'] + " " + df['entity_text'] + " " + df['entity_text']

def chunk_text(text, size=80):
    words = text.split()
    return [" ".join(words[i:i+size]) for i in range(0, len(words), size)]

rows = []

for _, row in df.iterrows():
    chunks = chunk_text(row['enhanced_text'])
    for chunk in chunks:
        rows.append({
            "subreddit": row['subreddit'],
            "text": chunk
        })

df_chunks = pd.DataFrame(rows)
print("Chunked size:", len(df_chunks))

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
import umap
import hdbscan

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

umap_model = umap.UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric='cosine',
    random_state=42
)

hdbscan_model = hdbscan.HDBSCAN(
    min_cluster_size=20,
    min_samples=5,
    cluster_selection_method='eom',
    prediction_data=True
)

vectorizer_model = CountVectorizer(
    ngram_range=(1,2),
    stop_words='english',
    min_df=2,
    max_df=0.95
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(df_chunks['text'].tolist())

df_chunks['topic'] = topics

topic_info = topic_model.get_topic_info()
print(topic_info.head(15))

from collections import Counter

def get_topic_entities(df):
    topic_entities = {}

    for topic in df['topic'].unique():
        subset = df[df['topic'] == topic]['text']
        ents = []

        for text in subset:
            doc = nlp(text)
            ents.extend([ent.text.lower() for ent in doc.ents])

        topic_entities[topic] = Counter(ents).most_common(5)

    return topic_entities

topic_entities = get_topic_entities(df_chunks)

for topic, ents in topic_entities.items():
    print(f"\nTopic {topic} Entities:", ents)

topic_model.visualize_topics()
topic_model.visualize_barchart()
topic_model.visualize_hierarchy()

for topic in df_chunks['topic'].value_counts().index[:5]:
    print(f"\n====== Topic {topic} ======")
    samples = df_chunks[df_chunks['topic'] == topic]['text'].sample(3)

    for s in samples:
        print("-", s[:300])

# Topic Diversity
def topic_diversity(model, top_n=10):
    topics = model.get_topics()
    words = []

    for topic in topics:
        if topic != -1:
            words.extend([word for word, _ in topics[topic][:top_n]])

    return len(set(words)) / len(words)

print("Topic Diversity:", topic_diversity(topic_model))

topic_model.visualize_topics()

topic_model.visualize_barchart(top_n_topics=10)

import matplotlib.pyplot as plt

df_chunks['topic'].value_counts().head(15).plot(kind='bar')
plt.title("Top Topic Frequencies")
plt.show()

topic_sub = pd.crosstab(df_chunks['topic'], df_chunks['subreddit'])

import seaborn as sns
plt.figure(figsize=(10,8))
sns.heatmap(topic_sub, cmap="coolwarm")
plt.title("Topic Distribution Across Subreddits")
plt.show()

for topic in list(topic_entities.keys())[:5]:
    print(f"\nTopic {topic}:")
    print(topic_entities[topic])

from wordcloud import WordCloud

for topic in df_chunks['topic'].value_counts().index[:3]:
    text = " ".join(df_chunks[df_chunks['topic']==topic]['text'])

    wc = WordCloud(width=800, height=400).generate(text)

    plt.imshow(wc)
    plt.axis("off")
    plt.title(f"Topic {topic}")
    plt.show()

for topic in df_chunks['topic'].value_counts().index[:3]:
    print(f"\n====== Topic {topic} Stories ======")

    samples = df_chunks[df_chunks['topic']==topic]['text'].sample(3)

    for s in samples:
        print("-", s[:300])

topic_model.visualize_heatmap()

nr_topics = 12  # you can try 10–15 depending on results

topic_model.reduce_topics(df_chunks['text'], nr_topics=nr_topics)

# Update topics
df_chunks['topic'] = topic_model.topics_

print(df_chunks['topic'].value_counts())

def generate_topic_labels(model):
    labels = {}

    for topic in model.get_topics().keys():
        if topic == -1:
            continue

        words = [word for word, _ in model.get_topic(topic)[:5]]

        label = " / ".join(words[:3])  # concise label
        labels[topic] = label

    return labels

topic_labels = generate_topic_labels(topic_model)

for t, label in topic_labels.items():
    print(f"Topic {t}: {label}")

from collections import Counter

def enhance_labels_with_ner(df, topic_labels):
    final_labels = {}

    for topic in df['topic'].unique():
        if topic == -1:
            continue

        subset = df[df['topic'] == topic]['text']
        ents = []

        for text in subset:
            doc = nlp(text)
            ents.extend([ent.text.lower() for ent in doc.ents])

        common_ents = [e for e, _ in Counter(ents).most_common(3)]

        base_label = topic_labels.get(topic, "")

        final_labels[topic] = base_label + " | " + ", ".join(common_ents)

    return final_labels

final_topic_labels = enhance_labels_with_ner(df_chunks, topic_labels)

for t, label in final_topic_labels.items():
    print(f"\nTopic {t}: {label}")

df_chunks['topic_label'] = df_chunks['topic'].map(final_topic_labels)

import matplotlib.pyplot as plt

topic_counts = df_chunks['topic_label'].value_counts().head(10)

topic_counts.plot(kind='barh')
plt.title("Top Topics (Labeled)")
plt.xlabel("Frequency")
plt.gca().invert_yaxis()
plt.show()

for topic in df_chunks['topic'].value_counts().index:
    if topic == -1: # Skip topic -1 as it's an outlier topic without a specific label
        continue
    # Only take the top 5 meaningful topics for display
    if list(df_chunks['topic'].value_counts().index).index(topic) >= 5:
        break

    print(f"\n====== {final_topic_labels[topic]} ======")

    samples = df_chunks[df_chunks['topic'] == topic]['text'].sample(3)

    for s in samples:
        print("-", s[:300])

topic_summary = df_chunks.groupby(['topic', 'topic_label']).size().reset_index(name='count')
topic_summary = topic_summary.sort_values(by='count', ascending=False)

print(topic_summary)